authors:
  fabricebrito:
    name: Fabrice Brito
    description: Founder at Terradue | Earth Observation Specialist | Open Standards Advocate | Open Source Developer
    avatar: https://avatars.githubusercontent.com/fabricebrito
    slug: https://github.com/fabricebrito
    url: https://github.com/fabricebrito